apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  generation: 0
  image:
    dockerImageLayers: null
    dockerImageMetadata: null
    metadata:
      creationTimestamp: null
  kind: ImageStreamTag
  lookupPolicy:
    local: false
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/imported-from: image-registry.openshift-image-registry.svc:5000/openshift/mysql:8.0-el8
    creationTimestamp: null
    labels:
      app: mysql
      app.kubernetes.io/component: mysql
      app.kubernetes.io/instance: mysql
      db: mysql
    name: mysql:8.0-el8
  tag:
    annotations: null
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/openshift/mysql:8.0-el8
    generation: null
    importPolicy: {}
    name: 8.0-el8
    referencePolicy:
      type: ""
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"mysql:8.0-el8","namespace":"openshift"},"fieldPath":"spec.template.spec.containers[?(@.name==\"mysql\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mysql
      app.kubernetes.io/component: mysql
      app.kubernetes.io/instance: mysql
      db: mysql
    name: mysql
  spec:
    replicas: 1
    selector:
      matchLabels:
        db: mysql
        deployment: mysql
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
          sidecar.istio.io/inject: 'true'
        creationTimestamp: null
        labels:
          db: mysql
          deployment: mysql
      spec:
        containers:
        - env:
          - name: MYSQL_DATABASE
            value: inventory
          - name: MYSQL_PASSWORD
            value: mysql
          - name: MYSQL_ROOT_PASSWORD
            value: mysql89
          - name: MYSQL_USER
            value: mysql
          image: ' '
          name: mysql
          ports:
          - containerPort: 3306
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mysql
      app.kubernetes.io/component: mysql
      app.kubernetes.io/instance: mysql
      db: mysql
    name: mysql
  spec:
    ports:
    - name: 3306-tcp
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      db: mysql
      deployment: mysql
  status:
    loadBalancer: {}
kind: List
metadata: {}
