apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: inventory
      app.kubernetes.io/component: inventory
      app.kubernetes.io/instance: inventory
    name: openjdk
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: docker.io/library/openjdk:11.0.12-jdk-slim
      from:
        kind: DockerImage
        name: docker.io/library/openjdk:11.0.12-jdk-slim
      generation: null
      importPolicy: {}
      name: 11.0.12-jdk-slim
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: inventory
      app.kubernetes.io/component: inventory
      app.kubernetes.io/instance: inventory
    name: inventory
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: inventory
      app.kubernetes.io/component: inventory
      app.kubernetes.io/instance: inventory
    name: inventory
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: inventory:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/lumander/the-spring-inventory.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: openjdk:11.0.12-jdk-slim
      type: Docker
    triggers:
    - github:
        secret: MnQnQIegBjlkVtiwmCbV
      type: GitHub
    - generic:
        secret: jKeXXbP2n5abrDRDgwgo
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"inventory:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"inventory\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: inventory
      app.kubernetes.io/component: inventory
      app.kubernetes.io/instance: inventory
    name: inventory
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: inventory
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
          sidecar.istio.io/inject: 'true'
        creationTimestamp: null
        labels:
          deployment: inventory
      spec:
        containers:
        - env:
          - name: NAMESPACE
            value: staging
          image: ' '
          name: inventory
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: inventory
      app.kubernetes.io/component: inventory
      app.kubernetes.io/instance: inventory
    name: inventory
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deployment: inventory
  status:
    loadBalancer: {}
kind: List
metadata: {}
